<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Models\Geo;

use App\Models\Segment;
use App\Models\Category;
use App\Models\Assignment;
use App\Models\Organization;
use Illuminate\Support\Facades\DB;

class AssignmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('assignments')->delete();

		$geo     = Geo::getCountry('PE');

        $organization01 = Organization::where('name','Zona A Sur')->first();
        $organization02 = Organization::where('name','Zona B Sur')->first();
        $organization03 = Organization::where('name','Zona A Norte')->first();
        $organization04 = Organization::where('name','Zona B Norte')->first();
        $organization05 = Organization::where('name','Supervisor Sur')->first();
        $organization06 = Organization::where('name','Supervisor Norte')->first();
        
        $category01 = Category::where('code','V')->first();
        $category02 = Category::where('code','A')->first();
        $category03 = Category::where('code','B')->first();
        $category04 = Category::where('code','C')->first();

        $segment01 = Segment::where('code','HO')->first();
        $segment02 = Segment::where('code','CO')->first();
        
        //target_id #: 436
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 1,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 2,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 3,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 4,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 5,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 6,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 7,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 8,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 9,'category_id'  => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 10,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 11,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 12,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 13,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 14,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 15,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 16,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 17,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 18,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 19,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 20,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 21,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 22,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 23,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 24,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 25,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 26,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 27,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 28,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 29,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 30,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 31,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 32,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 33,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 34,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 35,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 36,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 37,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 38,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 39,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 40,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 41,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 42,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 43,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 44,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 45,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 46,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 47,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 48,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 49,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 50,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 51,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 52,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 53,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 54,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 55,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 56,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 57,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 58,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 59,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 60,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 61,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 62,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 63,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 64,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 65,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 66,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 67,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 68,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 69,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 70,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 71,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 72,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 73,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 74,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 75,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 76,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 77,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 78,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 79,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 80,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 81,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 82,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 83,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 84,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 85,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 86,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 87,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 88,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 89,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 90,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 91,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 92,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 93,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 94,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 95,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 96,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 97,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 98,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 99,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization01->id,'target_id' => 100,'category_id' => $category04->id,'segment_id' => $segment02->id));
        


        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 101,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 102,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 103,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 104,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 105,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 106,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 107,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 108,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 109,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 110,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 111,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 112,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 113,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 114,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 115,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 116,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 117,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 118,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 119,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 120,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 121,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 122,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 123,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 124,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 125,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 126,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 127,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 128,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 129,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 130,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 131,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 132,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 133,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 134,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 135,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 136,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 137,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 138,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 139,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 140,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 141,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 142,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 143,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 144,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 145,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 146,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 147,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 148,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 149,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 150,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 151,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 152,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 153,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 154,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 155,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 156,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 157,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 158,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 159,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 160,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 161,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 162,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 163,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 164,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 165,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 166,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 167,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 168,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 169,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 170,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 171,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 172,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 173,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 174,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 175,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 176,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 177,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 178,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 179,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 180,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 181,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 182,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 183,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 184,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 185,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 186,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 187,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 188,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 189,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 190,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 191,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 192,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 193,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 194,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 195,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 196,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 197,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 198,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 199,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization02->id,'target_id' => 200,'category_id' => $category04->id,'segment_id' => $segment02->id));
        

        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 201,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 202,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 203,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 204,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 205,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 206,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 207,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 208,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 209,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 210,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 211,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 212,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 213,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 214,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 215,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 216,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 217,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 218,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 219,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 220,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 221,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 222,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 223,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 224,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 225,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 226,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 227,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 228,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 229,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 230,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 231,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 232,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 233,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 234,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 235,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 236,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 237,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 238,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 239,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 240,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 241,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 242,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 243,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 244,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 245,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 246,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 247,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 248,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 249,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 250,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 251,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 252,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 253,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 254,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 255,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 256,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 257,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 258,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 259,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 260,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 261,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 262,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 263,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 264,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 265,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 266,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 267,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 268,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 269,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 270,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 271,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 272,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 273,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 274,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 275,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 276,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 277,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 278,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 279,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 280,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 281,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 282,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 283,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 284,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 285,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 286,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 287,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 288,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 289,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 290,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 291,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 292,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 293,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 294,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 295,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 296,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 297,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 298,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 299,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization03->id,'target_id' => 300,'category_id' => $category04->id,'segment_id' => $segment02->id));
        

        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 301,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 302,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 303,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 304,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 305,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 306,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 307,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 308,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 309,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 310,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 311,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 312,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 313,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 314,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 315,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 316,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 317,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 318,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 319,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 320,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 321,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 322,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 323,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 324,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 325,'category_id' => $category01->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 326,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 327,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 328,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 329,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 330,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 331,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 332,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 333,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 334,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 335,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 336,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 337,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 338,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 339,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 340,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 341,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 342,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 343,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 344,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 345,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 346,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 347,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 348,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 349,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 350,'category_id' => $category02->id,'segment_id' => $segment01->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 351,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 352,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 353,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 354,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 355,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 356,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 357,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 358,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 359,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 360,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 361,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 362,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 363,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 364,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 365,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 366,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 367,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 368,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 369,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 370,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 371,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 372,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 373,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 374,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 375,'category_id' => $category03->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 376,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 377,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 378,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 379,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 380,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 381,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 382,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 383,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 384,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 385,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 386,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 387,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 388,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 389,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 390,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 391,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 392,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 393,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 394,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 395,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 396,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 397,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 398,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 399,'category_id' => $category04->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization04->id,'target_id' => 400,'category_id' => $category04->id,'segment_id' => $segment02->id));
        
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 401,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 402,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 403,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 404,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 405,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 406,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 407,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 408,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 409,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 410,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 411,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 412,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 413,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 414,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 415,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 416,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 417,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization05->id,'target_id' => 418,'category_id' => $category02->id,'segment_id' => $segment02->id));

        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 419,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 420,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 421,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 422,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 423,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 424,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 425,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 426,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 427,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 428,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 429,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 430,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 431,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 432,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 433,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 434,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 435,'category_id' => $category02->id,'segment_id' => $segment02->id));
        Assignment::create(array('geo_id' => $geo->id,'organization_id' => $organization06->id,'target_id' => 436,'category_id' => $category02->id,'segment_id' => $segment02->id));
        
        
    }
}
